
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.30.0/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:86 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 25.1.0 - arm64
...
